name: CavityFormation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - parmed
  - mdtraj
  - numpy
  - scipy
  - notebook
  - matplotlib
  - cython
  - openmm
  - openff-toolkit
