name: CavityFormation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - openmm=7.7
  - openmmtools
  - parmed
  - mdtraj
  - numpy
  - scipy
  - notebook
  - matplotlib
  - cython
